export default {
  showHeader:({commit})=>{
    commit('showHeader')
  },
  hideHeader:({commit})=>{
    commit('hideHeader')
  },
  showFooter:({commit})=>{
    commit('showFooter')
  },
  hideFooter:({commit})=>{
    commit('hideFooter')
  },
  showCenter:({commit})=>{
    commit('showCenter')
  },
  hideCenter:({commit})=>{
    commit('hideCenter')
  },
}